# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ðŸ‘‹ Welcome to the project!ðŸš€âš¡
  
  
  Thank you and congratsðŸŽ‰ for opening your very first issue in this project. Please adhere to our [Code of Conduct](https://github.com/sairish2001/makesmatheasy/blob/main/CODE_OF_CONDUCT.md).
  Please make sure not to start working on the issue, unless you get assigned to it.ðŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >

  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
